version: '3.8'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:6-alpine
    env_file:
      - .env
volumes:
  db_data:
